### ISSUE TITLE
Support for `musl` (alternative libc implementation)

### ISSUE THREAD

**Issue by chongkong** [ioi/isolate#48]
Hello, I'm trying to use `isolate` in an alpine-linux docker image. Alpine linux uses `musl` for the libc implementation, and there's a difference in `ftw.h` implementation between [`musl`](http://git.musl-libc.org/cgit/musl/tree/src/misc/nftw.c) and [`glibc`](https://github.com/lattera/glibc/blob/master/io/ftw.h): `FTW_CONTINUE` enum flag only exists in `glibc/ftw.h`.

`FTW_CONTINUE` is used in `util.c` so I cannot directly compile this unless you define `FTW_CONTINUE` explicitly, but I'm a newbie in linux and I don't know the proper way to fix the problem, so I'm creating the issue.

**Comment by seirl** [comment]
So, I think the way `nftw` is currently used is slightly incorrect.

Basically, `nftw` by default continues if the function given in parameter returns 0, and stops if it returns a non-zero value. This behavior can be changed with a glibc-specific flag, `FTW_ACTIONRETVAL`, which means instead of returning 0 or non-zero, you return `FTW_CONTINUE`, `FTW_STOP` or some other values.

In isolate, `FTW_CONTINUE` is used although `FTW_ACTIONRETVAL` isn't given as a flag. It just happens to work because `FTW_CONTINUE` is defined as 0, but it's an incorrect use of the GNU extension.

Since we don't use the capabilities offered by `FTW_ACTIONRETVAL`, I think the fix here is just:

```diff
diff --git a/util.c b/util.c
index 9f4cd70..07180ac 100644
--- a/util.c
+++ b/util.c
@@ -83,7 +83,7 @@ static int rmtree_helper(const char *fpath, const struct stat *sb,
       if (unlink(fpath) < 0)
        die("Cannot unlink %s: %m", fpath);
     }
-  return FTW_CONTINUE;
+  return 0;
 }
 
 void
@@ -101,7 +101,7 @@ static int chowntree_helper(const char *fpath, const struct stat *sb UNUSED,
   if (lchown(fpath, chown_uid, chown_gid) < 0)
     die("Cannot chown %s: %m", fpath);
   else
-    return FTW_CONTINUE;
+    return 0;
 }
 
 void

```

**Comment by chongkong** [comment]
Thanks for your explanation! It seems you haven't created pr for this, so I made #49. If you mind me creating pr for your suggestion you can always create your own and I'll close mine.

**Comment by seirl** [comment]
No worries. If you want to credit me in your commit, you can do `git commit --amend`, add a line containing `Co-authored-by: Antoine Pietri <antoine.pietri1@gmail.com>` and then push -f on your branch.

**Comment by chongkong** [comment]
Wow, I didn't know you can add multiple authors for a commit. Check [this](https://github.com/ioi/isolate/pull/49/commits/a7ee41962fb858496b26cb8c7cc268461b03181c)
