### ISSUE TITLE
Transferring stdin

### ISSUE THREAD

**Issue by Oleg-Arkhipov** [ioi/isolate#55]
Is it possible to start software with interactive CLI and type commands from terminal?
I tried to run `isolate --run -- /usr/bin/php -a` (interactive PHP shell), but my input makes no effect.

**Comment by gollux** [comment]
Not at the moment. With no --stdin/--stdout option given, isolate inherits the
standard input/output from the parent process, but if it is connected to
a terminal, tty management in the kernel kicks in. Since the isolated process
runs in a separate session, it is considered a background process, so it is
stopped when it tries to read from the terminal.

This is similar to what happens when you run "cat &" in the shell and I do
not see any easy way to avoid it.

**Comment by yuta0801** [comment]
This works for me:
```
$ cat | isolate -p --run -- $(which node) -i
Welcome to Node.js v14.5.0.
Type ".help" for more information.
> 
Error: Could not get the home directory.
REPL session history will not be persisted.
> 1 + 1
2
```

**Comment by hermanzdosilovic** [comment]
@gollux why does @yuta0801 solution work?
