### ISSUE TITLE
How to measure memory on a c++ program.

### ISSUE THREAD

**Issue by Vasilut** [ioi/isolate#56]
Hi. I have the next program:

#include <iostream>
using namespace std;

int main()
{
	int x[1000000];
	for(int i = 0; i < 500000000; ++i);
	
	cout << "Good life";
	
	return 0;
}

I want to measure the memory and the time for my program. I used the following command:

./isolate --cg --meta=/tmp/log4.txt --time=1 --run -- prog

In my log4.txt i have the next values:
time:0.844
time-wall:0.898
max-rss:3052
csw-voluntary:1
csw-forced:96
cg-mem:536

What represent the value 536 (cg-mem) ? If I make a short memory calculation of my array (x[1000000]) i will have ~3500kb of memory.

How I can measure the memory ?
I'm using version 1.4.1.

Thanks.

**Comment by hermanzdosilovic** [comment]
Hi @Vasilut,

let me try to explain you what happened here.

I have run your code in [Judge0 IDE](https://ide.judge0.com/?ABTauBsUFeGBkHyfAzaOj2dmMNax), an online code editor that uses `isolate` as sandbox. And as you can see your program used only 252 KB of memory because GCC compiler didn't even generate code for array declaration in line 7. You can see that for yourself using [Compiler Explorer](https://godbolt.org/g/TckuXe). So even with no optimization `-O0` compiler is smart enough to see that there is no need to allocate stack memory for `x` because it is not used. If you change `-O0` to `-O2` you will see that compiler will optimize your code even further and won't even generate code for `for` loop in line 8 [[link](https://godbolt.org/g/yBV4rC)].

If we modify your code slightly [[link](https://ide.judge0.com/?ADaP6PkJszRo7vhnNjyabNp8faUQ)] you will see that this program now uses 4200 KB of memory. [Godbolting](https://godbolt.org/g/tL1s2S) this code show that with `-O0` flag compiler generated code as you expected. With `-O2` flag that is not the case [[link](https://godbolt.org/g/B13eWA)]. Simple modification of this program will make compiler generate expected code even with `-02` flag [[link](https://ide.judge0.com/?AJT6y0otMQcJSx5TGHqV4Zum8O9s)] [[link](https://godbolt.org/g/FYqcsi)].

I hope you now understand why isolate showed you results you got. :smiley: 

BR,
Herman

**Comment by Vasilut** [comment]
Hi Herman.

Thanks for your response.
I understand now why the memory was not alocated in my case.
Still, I have one questions. Regarding the code that consumes 4200 Kb of memory:



#include <iostream>
#include <fstream>
using namespace std;

int main()
{
	int x[1000000];
    for(int i = 0; i < 500000000; ++i) 
    {
        if (i < 1000000)
		{
            x[i] = i;  
		}
	}
	
	cout << " Good 3l";
	
	return 0;
}

When I ran the following command: **./isolate --cg --meta=/tmp/logo.txt  --time=1.5 --run -- prog** 
I got the next result:
time:1.026
time-wall:1.247
max-rss:6932
csw-voluntary:1
csw-forced:2287
**cg-mem:17604**
Why I'm getting 17604 (I guess are 17604Kb), no ? 
Also, If I put --cg-mem=15000,  the program does not return memory limit exceeded.

Thanks.
Lucian

**Comment by hermanzdosilovic** [comment]
I am not sure. I think that @gollux, @bblackham or @seirl know the exact answer.

**Comment by stefano-maggiolo** [comment]
Not sure why you get such a high cg-memory usage (yes, it's about 17MiB), I get ~500KiB with -O2 and ~4.2MiB with -O0, similar to Herman.

The reason it doesn't fail with exceeded memory is most likely that you have swap enabled. Afaiu --cg-mem limits physical memory, but if you have swap enabled it will just swap more (with this workload it's not going to make a difference in running time, but an average program will take much more time.

cg-mem in the reporting instead is a maximum between `memory.max_usage_in_bytes` and `memory.memsw.max_usage_in_bytes`, which I assume means it takes the maximum between the max physical memory and the max swap used during the running time of the program.

Another similar unexpected situation with --cg-mem is, for example, when you declare a big array but you use only a part of it - this is not going to trigger memory limits even with swap disabled because the full array is never mapped fully in physical memory, just the pages you are actually using.

**Comment by chongkong** [comment]
I think `max_rss` (max resident set size; process RAM usage) field gives you the approximated maximum memory usage in kilobytes.

**Comment by Vasilut** [comment]
Thanks @stefano-maggiolo  and @hermanzdosilovic  for your answers. I will close the issue.
