### ISSUE TITLE
Measuring cache misses with perf

### ISSUE THREAD

**Issue by Teyras** [ioi/isolate#62]
I'm trying to read the cache miss counter of a program running in isolate with perf, but the result is always zero. I suspect this might have something to do with the program being in a cgroup, but that's just a thought. Is there a way to make perf work?

```
isolate -b 1 --cg --init
perf stat -e L1-dcache-load-misses isolate -b 1 --cg --cg-timing --run /usr/bin/ls
```

**Comment by bblackham** [comment]
Try `echo 0 > /proc/sys/kernel/perf_event_paranoid`. See https://www.kernel.org/doc/Documentation/sysctl/kernel.txt for details

**Comment by Teyras** [comment]
It worked, thank you very much! However, weird things still happen: `ls` in an isolate box reports about 1000 cache misses, and when I run it outside of a box, I get around 30000 cache misses. I think I'm listing the same directory...

**Comment by bblackham** [comment]
My guess it that because isolate is suid-root but perf is launched as a normal user, the perf counters stop the moment that it becomes root (i.e, a few thousand instructions into launching the binary. I have no authorative source to back up my theory, but I bet the kernel source will show this. If you run perf as root, the counters look right.

**Comment by Teyras** [comment]
Hmm, running perf as root seems to do the trick. I'm closing this, thanks for your help!
